# Generated by Django 4.0.4 on 2024-05-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_playlist_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='singer',
            field=models.TextField(null=True),
        ),
    ]
