# Generated by Django 4.0.4 on 2024-05-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_usermusic_genre_alter_usermusic_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='trackurl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='genre',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermusic',
            name='singer',
            field=models.CharField(max_length=1000),
        ),
    ]
