# Generated by Django 4.0.4 on 2024-05-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_track_trackurl_alter_usermusic_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='published_date',
            field=models.CharField(max_length=255),
        ),
    ]
