# Generated by Django 4.0.4 on 2024-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_userprofileinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusic',
            name='singer',
            field=models.TextField(),
        ),
    ]
