# Generated by Django 4.0.4 on 2024-06-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_usermusic_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='albumId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='aritstId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
