# Generated by Django 4.0.4 on 2024-06-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_track_albumid_track_aritstid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='aritstId',
            new_name='artistId',
        ),
    ]
